Repository pbclife/gitopener.vercel.app, pull requests merged in 2023-03, with the labels that each got.

#118 profile addition: updated priyankar's profile
  contribution/priyankarpal.mdx
  docs/guides/starting-contribution/hello-world.mdx
Labels: Profile Addition

#121 ci: added a gh action to upgrade dependencies
  .github/workflows/depen-update.yml
  package.json
  yarn.lock
Labels: ci: gh action

#124 profile addition: updated my profile
  contribution/priyankarpal.mdx
Labels: Profile Addition

#131 Create SajjanYadav.mdx
  contribution/SajjanYadav.mdx
Labels: Profile Addition

#134 Corrected spelling and pucntuation in heading.mdx
  docs/home/heading.mdx
Labels: documentation, improvement

#107 Create mishba-ai.mdx
  contribution/mishba-ai.mdx
Labels: Profile Addition

#135 Create AniketNS.mdx
  contribution/AniketNS.mdx
Labels: Profile Addition
