Repository pbclife/gitopener.vercel.app, pull requests merged in 2023-01, with the labels that each got.

#2 feat: Rest API server with mongoose
  api/axios.ts
  lib/contributors.ts
  package.json
  server/config/octokit.ts
  server/controllers/contributors.ts
  server/db/connectDB.ts
  server/errors/badRequest.ts
  server/errors/customError.ts
  server/errors/forbidden.ts
  server/errors/index.ts
  server/errors/notFound.ts
  server/errors/unauthorized.ts
  server/middlewares/errorHandler.ts
  server/models/contributors.ts
  server/validator/assertionGuards.ts
  src/pages/api/hello.ts
  src/pages/api/v1/contributors/[contId].ts
  src/pages/api/v1/contributors/index.ts
  src/pages/contributors/index.tsx
  src/pages/index.tsx
  tsconfig.json
  types/assertion.ts
  types/contributors.ts
  yarn.lock
Labels: enhancement, feat / approved

#6 bug-fix: fixed api routing issue with mongoose in deployment
  config/axios.ts
  lib/contributors.ts
  server/controllers/contributors.ts
  server/db/connectDB.ts
  src/pages/api/v1/contributors/[contId].ts
  src/pages/contributors/[contId].tsx
  src/pages/contributors/index.tsx
Labels: bug

#9 feat: Dark Theme feature
  package.json
  src/components/header/index.tsx
  src/components/hero/links.tsx
  src/components/hero/logo-section.tsx
  src/components/hero/text-section.tsx
  src/components/icons/git-opener.tsx
  src/components/layouts/main.tsx
  src/components/navbar/index.tsx
  src/components/navbar/theme.tsx
  src/components/utilities/dot.tsx
  src/components/utilities/pop-button.tsx
  src/components/utilities/pop.tsx
  src/components/utilities/typo-component.tsx
  src/context/theme-context.tsx
  src/hooks/useProgressBar.ts
  src/pages/_app.tsx
  src/pages/contributors/index.tsx
  src/pages/index.tsx
  src/styles/base.css
  tailwind.config.js
  tsconfig.json
  yarn.lock
Labels: feat / approved

#13 feat: Complete Layout Design
  package.json
  src/components/header/index.tsx
  src/components/icons/git-opener.tsx
  src/components/layouts/main.tsx
  src/components/menu/index.tsx
  src/components/menu/menu-list.tsx
  src/components/navbar/index.tsx
  src/components/navbar/theme-button.tsx
  src/components/utilities/glow.tsx
  src/components/utilities/logo.tsx
  src/components/utilities/tooltip.tsx
  src/data/menu-links.ts
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/index.tsx
  src/styles/base.css
  src/styles/globals.css
  tailwind.config.js
  tsconfig.json
  yarn.lock
Labels: enhancement

#14 feat: Contributor page
  lib/contributors.ts
  lib/date.ts
  next.config.js
  package.json
  server/models/contributors.ts
  server/models/validation/contributor.validation.ts
  src/components/contributorpage/ContributorComp.tsx
  src/components/contributorpage/NewContributrs.tsx
  src/components/contributorpage/OldContributrs.tsx
  src/components/contributorpage/PopularContributrs.tsx
  src/components/contributorpage/RenderContributors.tsx
  src/components/icons/early-birds.tsx
  src/components/icons/fresh-leaf.tsx
  src/components/icons/star-man.tsx
  src/components/layouts/main.tsx
  src/components/layouts/represent/index.tsx
  src/components/menu/index.tsx
  src/components/menu/menu-list.tsx
  src/components/utilities/SmoothLink.tsx
  src/pages/contributors/index.tsx
  src/styles/base.css
  src/styles/utilities.css
  tsconfig.json
  yarn.lock
Labels: enhancement, feat / approved

#23 bug-fix: no more overlapping in small devices
  src/components/menu/index.tsx
  src/components/menu/menu-list.tsx
  src/components/navbar/theme-button.tsx
  src/components/utilities/tooltip.tsx
  src/hooks/useArea.ts
Labels: bug

#25 feat: Sync total contributors count with database
  server/controllers/contributors.ts
  src/components/hero/text-section.tsx
  src/context/headerContext.tsx
  src/pages/_app.tsx
  src/pages/api/v1/contributors/total.ts
Labels: enhancement, feat / approved

#38 Update readme (need some fix though)
  CONTRIBUTING.md
  README.md
Labels: documentation, enhancement

#45 feat: designed home page
  docs/heading.mdx
  docs/installation.mdx
  docs/tech-stack.mdx
  lib/contributors.ts
  lib/read-docs.ts
  package.json
  src/components/icons/issue.tsx
  src/components/utilities/RenderMdx.tsx
  src/pages/index.tsx
  src/styles/base.css
  tailwind.config.js
  types/file.d.ts
  yarn.lock
Labels: enhancement, feat / approved
